// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    module("add");
    return test("Graph Construction", function() {
      var g;
      g = graphical.graph(null, null);
      deepEqual(g.vertices(), []);
      g = graphical.graph(['a'], null);
      deepEqual(g.vertices(), ['a']);
      g = graphical.graph(['a', 'b'], null);
      deepEqual(g.vertices(), ['a', 'b']);
      g = graphical.graph(['a', 'a'], null);
      return deepEqual(g.vertices(), ['a']);
    });
  });

}).call(this);
